config/routes.rb
Rails.application.routes.draw do

  root 'weather#index'
  resources :weather, only: [:index, :new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User
  include ActiveModel::Model
  
  attr_accessor :country_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def create
    # Determine whether a cookie exists before making a new API call
    cookie_check = cookies[['Railsy Weather', params[:city], params[:country]].join('')].to_s.to_sym
    if cookie_check.present?
      @clean_weather = clean_hash_string(cookie_check.to_s)
      render :new
    else
      @weather = check_weather
      if weather_params[:city].empty?  
        flash[:notice] = "Oops, that doesn't appear to be a valid city. Please check for typos and try again."
        redirect_to new_weather_path
      elsif weather_params[:country].empty?  
        flash[:notice] = "Oops, your country must be selected in order to proceed."
        redirect_to new_weather_path
      elsif check_weather == false
        flash.now[:notice] = "Oops, that doesn't appear to be a valid city/country combo. Please try again."
        redirect_to new_weather_path
      else 
        set_session(@weather)
        @clean_weather = clean_hash_string(@weather.to_s)
      end
    end
  end

  def weather_params
    params.permit(:city, :country)
  end

  def check_weather
    CheckWeather.new(params[:city], params[:country]).call
  end

  def set_session(weather)
    # Set cookie with city and country converted to strings
    cookies[['Railsy Weather', params[:city], params[:country]].join('')].to_s.to_sym
    # Sets 30 minute time limit for data retrieved per call made
    weather_group = {value: weather, expires: 30.minutes.from_now}
    cookies[['Railsy Weather', params[:city], params[:country]].join('')] = weather_group
    # Sets and returns weather object
    @weather = cookies[['Railsy Weather', params[:city], params[:country]].join('')]
    return @weather
  end

  def clean_hash_string(dirty_hash)
    clean_weather = JSON.parse(dirty_hash.gsub('=>', ':'), object_class: OpenStruct)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def convert_to_fahrenheit(kelvin)
    fahrenheit = (kelvin * (9.0 / 5.0)) - 459.67
    return fahrenheit.round
  end

  def clean_hash_string(dirty_hash)
    @clean_weather = JSON.parse(dirty_hash.gsub('=>', ':'), object_class: OpenStruct)
  end
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <p><%= message %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsy Weather</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/weather/index.html.erb
<h1 class='welcome'>Welcome to Railsy Weather!</h1>
<h4>Find Your Local Weather by Making a Selection Below:</h4>

<div id="location-select">
  <%= form_for User.new, url: weather_index_path do |f| %>

    <% I18n.with_locale(:countries) do %>
      <p id='country'>
      <%= select_tag(:country, options_for_select(
          ISO3166::Country.codes.sort.map { |code| [ISO3166::Country.new(code).name, code] }, 
          @country
        ), {:include_blank => '-- Select Your Country --', required: true}) %>
      </p>
    <% end %>

    <span id='city'>
      <%= text_field_tag 'city', nil, placeholder: 'Enter your city...', required: true %>
    </span>
    <span id='submit-btn'>
      <%= submit_tag "Check Weather" %>
    </span>

  <% end %>
</div>

app/views/weather/new.html.erb
<% unless @clean_weather.nil? %>
<h1 class='current'>Current Weather</h1>

<div class='panel'>
  <h2 class='city' id='city'><%= @clean_weather.name %>, <%= @clean_weather.sys.country %></h2>
  <div class='weather' id='weather'>
    <div class='group-container'>
      <div class='group left'>
        <h3 id='dt'><%= Time.at(@clean_weather.dt).strftime("%b %d %Y") %></h3>
        <h3 id='description'><%= @clean_weather.weather[0].description %></h3>
      </div>
      <div class='group right'>
        <h3 id='wind'>Wind <%= @clean_weather.wind.speed %> mph</h3>
        <h3 id='humidity'>Humidity <%= @clean_weather.main.humidity %>%</h3>
      </div>
    </div>
    <div class='temperature' id='temperature'>
      <h1 class='temp' id='temp'>
        <span id='num'><%= convert_to_fahrenheit(@clean_weather.main.temp) %></span>
        <span class='fahrenheit active' id='fahrenheit' href="">&deg;F</span>
      </h1>
    </div>
  </div>
  <div class='find-new'><%= link_to "Find a Different Location", root_path %></div>
</div>
<% end %>

<% if new_weather_path && @clean_weather.nil? -%>
  <div class="flash-notice">Oops, that doesn't appear to be a valid city/country combo. Please try again.</div>
  <div class='try-again'><%= link_to "Please Try Again", root_path %></div>
<% end %>